package io.github.jsoapdoc.model;

import java.util.List;

public class WsdlInfo {

    private String serviceName;
    private String description;
    private String version;
    private String[] rolesAllowed;
    private List<OperationInfo> operations;

    public WsdlInfo(String serviceName, List<OperationInfo> operations) {
        this.serviceName = serviceName;
        this.operations = operations;
    }

    public WsdlInfo() {
    }

    /**
     * Gets the name of the service.
     *
     * @return the name of the service.
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the name of the service.
     *
     * @param serviceName the name of the service.
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * Gets the operations exposed by the service.
     *
     * @return the operations exposed by the service.
     */
    public List<OperationInfo> getOperations() {
        return operations;
    }

    /**
     * Sets the operations exposed by the service.
     *
     * @param operations a list of OperationInfo objects representing the operations to be set.
     */
    public void setOperations(List<OperationInfo> operations) {
        this.operations = operations;
    }

    /**
     * Gets the description of the service, as provided by the user.
     *
     * @return the description of the service.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of the service. This description is provided by the user and is
     * not automatically generated by this library.
     *
     * @param description the description to be set.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the version of the service. This version is provided by the user and is
     * not automatically generated by this library.
     *
     * @return the version of the service.
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the version of the service. This version is provided by the user and is
     * not automatically generated by this library.
     *
     * @param version the version to be set.
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Gets the roles that are allowed access to the service.
     *
     * @return an array of role names that are allowed access.
     */
    public String[] getRolesAllowed() {
        return rolesAllowed;
    }

    /**
     * Sets the roles that are allowed access to the service.
     *
     * @param rolesAllowed an array of role names that are allowed access.
     */
    public void setRolesAllowed(String[] rolesAllowed) {
        this.rolesAllowed = rolesAllowed;
    }

}
